---
name: Synchronize CKAN record to dataset repository contribution.cff
description: 'This action synchronizes a CKAN record to a dataset repository contribution.cff file.'
inputs:
  ckan_server:
    description: 'CKAN server URL'
    required: false
    default: 'https://catalogue.hakai.org'
  record_id:
    description: 'Eye color of the Octocats'
    required: true
  outputs:
    description: 'The outputs of the action'
    required: false
    default: 'contribution.cff'
  outputs_format:
    description: 'The format of the outputs'
    required: false
    default: 'cff'
  commit:
    description: 'Commit the outputs to the repository'
    required: false
    default: 'true'
  branch:
    description: 'Branch to commit the outputs to'
    required: false
    default: 'main'
  branch_suffix:
    description: 'Suffix to append to the branch name'
    required: false
    default: 'update-contribution-cff'
  token:
    description: 'GitHub token'
    required: true
    default: '${{ secrets.GITHUB_TOKEN }}'
  base:
    description: 'Base branch to create the pull request against'
    required: false
    default: 'main'
  labels:
    description: 'Labels to add to the pull request'
    required: false
    default: 'automated'
  title:
    description: 'Title of the pull request'
    required: false
    default: 'Update contribution.cff'
  body:
    description: 'Body of the pull request'
    required: false
    default: |
      'This pull request updates the contribution.cff file.\
      It was generated by the hakai_ckan_records_conversion action.
      The action was triggered by the update of record with ID: \
      <${{inputs.ckan_server}}/datasets/${{ inputs.record_id }}>.'

runs:
  using: "composite"
  steps:
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      shell: bash
      run: pip install git+https://github.com/HakaiInstitute/hakai-ckan-records-conversion.git

    - name: Run conversion
      shell: bash
      run: |
        poetry run python hakai_ckan_records_conversion \
        --ckan-server ${{ inputs.ckan_server }} \
        --record-id ${{ inputs.record_id }} \
        --outputs ${{ inputs.outputs }} \
        --outputs-format ${{ inputs.outputs_format }}

    - name: Commit outputs
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: 'Update contribution.cff'
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
        branch: ${{ inputs.branch }}
        token: ${{ input.token }}
        base: ${{ inputs.base }}
        branch-suffix: ${{ inputs.branch_suffix }}
        labels: ${{ inputs.labels }}
